INTERNAL: more reliable publishing
Lamden/clove pull request #76
Opened 2018-02-19 16:29 UTC by trojkat

2018-02-19 17:17 UTC, szerepak requested changes

2018-02-19 17:17 UTC, szerepak commented on clove/utils/network.py
> +    time.sleep(0.1)
:trollface: [It used to be good, then men came to my pull request xD](https://github.com/Lamden/clove_dev/pull/14#discussion_r164156732)

2018-02-19 17:17 UTC, szerepak commented on clove/network/base.py
> +                    logger.debug('[%s] << Talking with this node', node)
<< Connection established with this node

2018-02-19 17:17 UTC, szerepak commented on clove/network/base.py
> +                    logger.debug('[%s] << Sending verack', node)
<< Sending version acknowledge message

2018-02-19 17:17 UTC, szerepak commented on clove/network/base.py
> +                    logger.debug('[%s] No response on verack: %s', node, e)
use `logger.exception` and this is not 100% true, because these errors can occur not only whilst sending verack but also when connection is establishing and version is sending (see indentation)

2018-02-19 17:17 UTC, szerepak commented on clove/network/base.py
> +        messages = [prefix + message for message in buffer.split(prefix) if message]
:+1:

2018-02-20 08:48 UTC, trojkat commented on clove/utils/network.py
> +    time.sleep(0.1)
This is a different case because receiving is on our side so no need for timeout here. We just want to wait and return what we've got.

2018-02-20 09:28 UTC, szerepak commented on clove/utils/network.py
> +    time.sleep(0.1)
same case but nvm

2018-02-20 09:43 UTC, szerepak approved these changes
Missed grammar error before, sorry :( Please fix it. Apart from that code looks spotless <3

2018-02-20 09:43 UTC, szerepak commented on bin/test-initial-transaction.py
> +        print_error('Something went wrong, transaction NOT published.')
**is** NOT

2018-02-20 09:43 UTC, szerepak commented on bin/test-participate-transaction.py
> +        print_error('Something went wrong, transaction NOT published.')
ditto

2018-02-20 09:43 UTC, szerepak commented on bin/test-redeem-transaction.py
> +        print_error('Something went wrong, transaction NOT published.')
ditto

2018-02-20 09:43 UTC, szerepak commented on bin/test-refund-transaction.py
> +        print_error('Something went wrong, transaction NOT published.')
ditto

2018-02-20 10:36 UTC, pafff approved these changes

2018-02-20 10:38 UTC, merged